PROBLEM 1

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
a = np.empty((2, 2))
print(a)

[[4.77781646e-310 0.00000000e+000]
 [3.60286887e+252 5.64531613e-311]]


2. Initialize an all one array with size 4X2.

In [ ]:
b = np.ones((4, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
c = np.full((3,3), 8)
print(c)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.zeros_like(array1)
print(array2)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
array1 = np.array([[2,3],[4,5]])
array2 = np.ones_like(array1)
print(array2)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
array1 = np.array(new_list)
print(array1)

[1 2 3 4]


PROBLEM 2

1.Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
array = np.arange(0, 947777777777777777777777777777777777777).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3.Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
array = np.eye(3).reshape(3,3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
array = np.random.random(30)
print(array)
mean = array.mean()
print(mean)

[0.05970428 0.83279429 0.73539873 0.09547311 0.12447721 0.14931367
 0.33515929 0.94590286 0.83181607 0.86041429 0.48678231 0.92656087
 0.31597146 0.2339244  0.20050473 0.21581805 0.30903753 0.96730834
 0.36873678 0.06571927 0.50406738 0.369948   0.31360255 0.19031846
 0.83816775 0.87134305 0.14938004 0.40535314 0.05260901 0.00123534]
0.42522807497481263


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
array = np.random.randint(0, 50, size=(10, 10))
print(array)
min_val = array.min()
max_val = array.max()
print("Minimum value:", min_val)
print("Maximum value:", max_val)

[[ 0 44 18 16 18 45  7 16 37  3]
 [15 39 28 31  0  9 14 34 40  6]
 [32 20 25 18 18  0 48  3 10 49]
 [25 13  6 17 22 38  4 19 32 33]
 [40 13 22 42 31  9 12  0 27 31]
 [37  9 23 40 12 37 34 27 13  8]
 [44 38 48 22 31 46 12 17 46 29]
 [30  7 33 46 17 34 13 19 45 23]
 [43  5  3 44 28 39 15 25 20 26]
 [23  9 11 11 49  0 48 18 34 10]]
Minimum value: 0
Maximum value: 49


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print(reversed_arr)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with border 1 and inside 0:\n", border_array)


2D array with border 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


PROBLEM 3

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x + y
print(result)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
result = x - y
print(result)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
mult1 = x*2
mult2 = y*3
mult3 = v*4
mult4 = w*5
print(mult1)
print(mult2)
print(mult3)
print(mult4)

[[ 2  4]
 [ 6 10]]
[[15 18]
 [21 24]]
[36 40]
[55 60]


4. Find the square of each element of the array.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

x_square = np.square(x)
y_square = np.square(y)
v_square = np.square(v)
w_square = np.square(w)

print("Square of x:", x_square)
print("Square of y:", y_square)
print("Square of v:", v_square)
print("Square of w:", w_square)


Square of x: [[ 1  4]
 [ 9 25]]
Square of y: [[25 36]
 [49 64]]
Square of v: [ 81 100]
Square of w: [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot1 = np.dot(v, w)
dot2 = np.dot(x, v)
dot3 = np.dot(x, y)

print("Dot product of v and w:", dot1)
print("Dot product of x and v:", dot2)
print("Dot product of x and y:", dot3)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6.Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result1 = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n",result1)

v = np.array([9, 10])
w = np.array([11, 12])

result2 = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("Concatenation of v and w along columns:\n", result2)


Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
Answer. We will get a error if we directly concatenate x and v however if we reshape v we can solve it.

In [ ]:
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Reshape v to a 2D array with 1 row and 2 columns
v_reshaped = v.reshape(1, 2)
print(v_reshaped)

# Concatenate x and v along the vertical axis (axis=0)
result = np.concatenate((x, v_reshaped), axis=0)

print(result)


[[ 9 10]]
[[ 1  2]
 [ 3  5]
 [ 9 10]]


PROBLEM 4


For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

1. Prove A.A^-1 = I.

In [ ]:
# Define the matrix A
A = np.array([[3, 4], [7, 8]])

# Calculating inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
I = np.dot(A, A_inv)

print("A * A^-1 =\n", I)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
# Define the matrix B
B = np.array([[5, 3], [2, 1]])

# Calculate AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

# Check if AB is not equal to BA
print("\nIs AB equal to BA?", np.array_equal(AB, BA))
print("Proved")


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]

Is AB equal to BA? False
Proved


3. Prove (AB)^T = B^TA^T

In [ ]:
# Calculate the transpose of AB and the product of B^T and A^T
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("Transpose of AB = (AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)

# Check if (AB)^T is equal to B^T * A^T
print("\nIs (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))


Transpose of AB = (AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [1]:
import numpy as np

# Define the matrices
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("The solution is:", X)


The solution is: [ 2.  1. -2.]
